# on Macs: symlink this to $HOME/Library/Application Support/lazygit/config.yml
git:
  diffRenderers:
    - command: delta --dark --paging=never --line-numbers
      name: unified
    - command: delta --dark --paging=never --line-numbers --side-by-side
      name: side-by-side
  commit:
    autoWrapCommitMessage: true
